on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy sources
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: Build plugin
        run: mvn clean package

      - name: Run unit tests
        run: mvn test

